require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - gemfiles/vendor/bundle/**/*

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/dummy/db/schema.rb
