require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

# RuboCop requires Ruby 2.4+ but this gem supports 2.3.
Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/dummy/db/schema.rb
