name: Build

on:
  push:

  # schedule on every day at 8:00 AM JST.
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          rubygems: latest
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Prepare database
        run: |
          bundle exec rails db:create
          bundle exec rails db:test:prepare
        working-directory: ./spec/dummy
      - name: Run RSpec
        run: bundle exec rspec

  version_compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2', 'head' ]
        rails: [ '6_0', '6_1', '7_0', 'head' ]
        exclude:
          # Rails 7- doesn't work on Ruby 3.1+
          - ruby:  '3.1'
            rails: '6_0'
          - ruby:  '3.1'
            rails: '6_1'
          - ruby:  '3.2'
            rails: '6_0'
          - ruby:  '3.2'
            rails: '6_1'
          - ruby: 'head'
            rails: '6_0'
          - ruby: 'head'
            rails: '6_1'

    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: latest
    - name: Prepare database
      run: |
        bundle exec rails db:create
        bundle exec rails db:test:prepare
      working-directory: ./spec/dummy
      env:
        BUNDLE_GEMFILE: ../../gemfiles/rails_${{ matrix.rails }}.gemfile
    - name: Run RSpec
      run: bundle exec rspec
